RelatedModels_pull_request
XCMachine/Rijs-museum pull request #12
Opened 2022-04-01 13:02 UTC by XCMachine

2022-04-04 09:42 UTC, Golemanova commented on RijsMuseum/app/src/main/java/com/example/rijsmuseum/adapter/RecyclerAdapter.kt
> +    private val cList: MutableList<CollectionsResource.ArtObjectResource> = mutableListOf()
I assume the resource is the raw object coming directly from the request. If that is the case, then you shouldn't use that here. Instead you should use the model from the domain package.

2022-04-04 09:42 UTC, Golemanova commented on RijsMuseum/app/src/main/java/com/example/rijsmuseum/fragments/ArtifactsFragment.kt
> +            override fun onItemClick(cList: CollectionsResource.ArtObjectResource) {
Again here. The resource models should be used only in the network module. In the presentation layer you should use your domain models.

2022-04-04 09:42 UTC, Golemanova commented on RijsMuseum/network/src/main/java/com/example/network/domain/mappers/CollectionsDetailsResourceMapper.kt
> +    fun getResourceObject(resource: CollectionsDetailsResource): ArtObject {
This method makes no sense. It basically does the same as the method above.

2022-04-05 14:37 UTC, stantt requested changes

2022-04-05 14:40 UTC, stantt approved these changes

2022-04-05 14:54 UTC, merged